[2025-05-23T22:41:29.792+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: punctuality_etl_dag.transform_data manual__2025-05-23T22:41:27.498684+00:00 [queued]>
[2025-05-23T22:41:29.796+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: punctuality_etl_dag.transform_data manual__2025-05-23T22:41:27.498684+00:00 [queued]>
[2025-05-23T22:41:29.796+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-23T22:41:29.865+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_data> on 2025-05-23 22:41:27.498684+00:00
[2025-05-23T22:41:29.868+0000] {standard_task_runner.py:57} INFO - Started process 946 to run task
[2025-05-23T22:41:29.870+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'punctuality_etl_dag', 'transform_data', 'manual__2025-05-23T22:41:27.498684+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/punctuality_etl_dag.py', '--cfg-path', '/tmp/tmpki0f6y51']
[2025-05-23T22:41:29.872+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask transform_data
[2025-05-23T22:41:29.881+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-23T22:41:29.902+0000] {task_command.py:415} INFO - Running <TaskInstance: punctuality_etl_dag.transform_data manual__2025-05-23T22:41:27.498684+00:00 [running]> on host 8ac5b706b4e9
[2025-05-23T22:41:29.944+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='punctuality_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T22:41:27.498684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-23T22:41:27.498684+00:00'
[2025-05-23T22:41:29.953+0000] {logging_mixin.py:151} INFO - Cleaned punctuality data saved to data/processed/punctuality_avg_cleaned.csv
[2025-05-23T22:41:29.953+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-23T22:41:29.959+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=punctuality_etl_dag, task_id=transform_data, execution_date=20250523T224127, start_date=20250523T224129, end_date=20250523T224129
[2025-05-23T22:41:29.969+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-23T22:41:29.982+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
